spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "1.0"

accounts:
  message: "Hello from accounts microservice"
  contactDetails:
    name: "Carlos Mejia - Product Owner"
    email: "carlosgarciahl@hotmail.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 555-5678