spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "2.0"

accounts:
  message: "Hello from accounts microservice"
  contactDetails:
    name: "Carlos Mejia - QA"
    email: "carlosgarciahl@hotmail.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 555-5678